module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('Groups', [{
    name: 'admin',
    aclEditUser: true,
    aclDeleteUser: true,
    aclAddUser: true,
    aclActivateUser: true,
    aclDeactivateUser: true,
    aclAddUserToGroup: true,
    aclCreateGroup: true,
    aclDeleteGroup: true,
    aclChangeGroupPermissions: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'default',
    aclEditUser: false,
    aclDeleteUser: false,
    aclAddUser: false,
    aclActivateUser: false,
    aclDeactivateUser: false,
    aclAddUserToGroup: false,
    aclCreateGroup: false,
    aclDeleteGroup: false,
    aclChangeGroupPermissions: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }, {
    name: 'test1',
    aclEditUser: false,
    aclDeleteUser: false,
    aclAddUser: true,
    aclActivateUser: false,
    aclDeactivateUser: false,
    aclAddUserToGroup: false,
    aclCreateGroup: false,
    aclDeleteGroup: false,
    aclChangeGroupPermissions: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }, {
    name: 'test2',
    aclEditUser: false,
    aclDeleteUser: true,
    aclAddUser: false,
    aclActivateUser: false,
    aclDeactivateUser: false,
    aclAddUserToGroup: false,
    aclCreateGroup: false,
    aclDeleteGroup: false,
    aclChangeGroupPermissions: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }, {
    name: 'test3',
    aclEditUser: false,
    aclDeleteUser: false,
    aclAddUser: false,
    aclActivateUser: false,
    aclDeactivateUser: false,
    aclAddUserToGroup: false,
    aclCreateGroup: true,
    aclDeleteGroup: false,
    aclChangeGroupPermissions: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }, {
    name: 'test4',
    aclEditUser: false,
    aclDeleteUser: false,
    aclAddUser: false,
    aclActivateUser: false,
    aclDeactivateUser: false,
    aclAddUserToGroup: false,
    aclCreateGroup: false,
    aclDeleteGroup: false,
    aclChangeGroupPermissions: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  }], {}),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('Groups', null, {}),
};
